-- MySQL Script generated by MySQL Workbench
-- Wed 13 Jun 2018 11:29:47 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mine_apple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mine_apple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mine_apple` DEFAULT CHARACTER SET utf8 ;
USE `mine_apple` ;

-- -----------------------------------------------------
-- Table `mine_apple`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `operacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_log_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`administrador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`produtor` (
  `id` INT NOT NULL,
  `cnpj` INT NOT NULL,
  `nomeFantasia` VARCHAR(255) NOT NULL,
  `razaoSocial` VARCHAR(255) NOT NULL,
  `telefone` INT NOT NULL,
  `raioEntrega` DOUBLE NOT NULL,
  `acesso` TINYINT(1) NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_produtor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`banco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banco_id` INT NOT NULL,
  `produtor_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `agencia` INT NOT NULL,
  `digito` INT NOT NULL,
  PRIMARY KEY (`id`, `banco_id`, `produtor_id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_conta_produtor1_idx` (`produtor_id` ASC),
  INDEX `fk_conta_banco1_idx` (`banco_id` ASC),
  CONSTRAINT `fk_conta_produtor1`
    FOREIGN KEY (`produtor_id`)
    REFERENCES `mine_apple`.`produtor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_banco1`
    FOREIGN KEY (`banco_id`)
    REFERENCES `mine_apple`.`banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `produtor_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `valor` DOUBLE NOT NULL,
  `minPorAssinatura` INT NOT NULL,
  `maxPorDia` INT NOT NULL,
  `freteMax` DOUBLE NOT NULL,
  `seg` TINYINT(1) NOT NULL,
  `ter` TINYINT(1) NOT NULL,
  `qua` TINYINT(1) NOT NULL,
  `qui` TINYINT(1) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `sab` TINYINT(1) NOT NULL,
  `dom` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`, `produtor_id`),
  INDEX `fk_produto_produtor1_idx` (`produtor_id` ASC),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto_produtor1`
    FOREIGN KEY (`produtor_id`)
    REFERENCES `mine_apple`.`produtor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mine_apple`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`consumidor` (
  `id` INT NOT NULL,
  `cpf` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `telefone` INT NULL,
  `acesso` TINYINT(1) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_consumidor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mine_apple`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cartao` (
  `id` INT NOT NULL,
  `numero` INT NOT NULL,
  `titular` VARCHAR(255) NOT NULL,
  `validade` DATE NOT NULL,
  `codigo` INT NOT NULL,
  `tipo` ENUM('c', 'd') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`estado` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sigla` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `estado_id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mine_apple`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`cep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`, `estado_id`),
  INDEX `fk_cep_cidade1_idx` (`cidade_id` ASC, `estado_id` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  CONSTRAINT `fk_cep_cidade1`
    FOREIGN KEY (`cidade_id` , `estado_id`)
    REFERENCES `mine_apple`.`cidade` (`id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep_id` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `cep_id`, `cidade_id`, `estado_id`),
  INDEX `fk_endereco_cep1_idx` (`cep_id` ASC, `cidade_id` ASC, `estado_id` ASC),
  CONSTRAINT `fk_endereco_cep1`
    FOREIGN KEY (`cep_id` , `cidade_id` , `estado_id`)
    REFERENCES `mine_apple`.`cep` (`id` , `cidade_id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consumidor_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `cep_id` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `frete` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `consumidor_id`, `endereco_id`, `cep_id`, `cidade_id`, `estado_id`),
  INDEX `fk_compra_consumidor1_idx` (`consumidor_id` ASC),
  INDEX `fk_compra_endereco1_idx` (`endereco_id` ASC, `cep_id` ASC, `cidade_id` ASC, `estado_id` ASC),
  CONSTRAINT `fk_compra_consumidor1`
    FOREIGN KEY (`consumidor_id`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_endereco1`
    FOREIGN KEY (`endereco_id` , `cep_id` , `cidade_id` , `estado_id`)
    REFERENCES `mine_apple`.`endereco` (`id` , `cep_id` , `cidade_id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`assinatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `consumidor_id` INT NOT NULL,
  `produtor_id` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `frete` DOUBLE NOT NULL,
  `notaFiscal` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `compra_id`, `consumidor_id`),
  INDEX `fk_assinatura_compra1_idx` (`compra_id` ASC, `consumidor_id` ASC),
  INDEX `fk_assinatura_produtor1_idx` (`produtor_id` ASC),
  CONSTRAINT `fk_assinatura_compra1`
    FOREIGN KEY (`compra_id` , `consumidor_id`)
    REFERENCES `mine_apple`.`compra` (`id` , `consumidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assinatura_produtor1`
    FOREIGN KEY (`produtor_id`)
    REFERENCES `mine_apple`.`produtor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consumidor_id` INT NOT NULL,
  `compra_id` INT NOT NULL,
  `assinatura_id` INT NOT NULL,
  `cartao_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `consumidor_id`, `compra_id`, `assinatura_id`, `cartao_id`),
  INDEX `fk_pagamento_cartao1_idx` (`cartao_id` ASC),
  INDEX `fk_pagamento_assinatura1_idx` (`assinatura_id` ASC, `compra_id` ASC, `consumidor_id` ASC),
  CONSTRAINT `fk_pagamento_cartao1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `mine_apple`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_assinatura1`
    FOREIGN KEY (`assinatura_id` , `compra_id` , `consumidor_id`)
    REFERENCES `mine_apple`.`assinatura` (`id` , `compra_id` , `consumidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`avaliacao` (
  `consumidor_id` INT NOT NULL,
  `compra_id` INT NOT NULL,
  `assinatura_id` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `comentario` VARCHAR(255) NULL,
  PRIMARY KEY (`consumidor_id`, `compra_id`, `assinatura_id`),
  CONSTRAINT `fk_avaliacao_assinatura1`
    FOREIGN KEY (`assinatura_id` , `compra_id` , `consumidor_id`)
    REFERENCES `mine_apple`.`assinatura` (`id` , `compra_id` , `consumidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `produtor_id` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `produto_id`, `categoria_id`, `produtor_id`),
  INDEX `fk_foto_produto1_idx` (`produto_id` ASC, `categoria_id` ASC, `produtor_id` ASC),
  CONSTRAINT `fk_foto_produto1`
    FOREIGN KEY (`produto_id` , `categoria_id` , `produtor_id`)
    REFERENCES `mine_apple`.`produto` (`id` , `categoria_id` , `produtor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`consumidor_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`consumidor_endereco` (
  `consumidor_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `cep_id` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`consumidor_id`, `endereco_id`, `cep_id`, `cidade_id`, `estado_id`),
  INDEX `fk_consumidor_endereco_endereco1_idx` (`endereco_id` ASC, `cep_id` ASC, `cidade_id` ASC, `estado_id` ASC),
  INDEX `fk_consumidor_endereco_consumidor1_idx` (`consumidor_id` ASC),
  CONSTRAINT `fk_consumidor_endereco_consumidor1`
    FOREIGN KEY (`consumidor_id`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumidor_endereco_endereco1`
    FOREIGN KEY (`endereco_id` , `cep_id` , `cidade_id` , `estado_id`)
    REFERENCES `mine_apple`.`endereco` (`id` , `cep_id` , `cidade_id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`cartao_consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cartao_consumidor` (
  `cartao_id` INT NOT NULL,
  `consumidor_id` INT NOT NULL,
  PRIMARY KEY (`cartao_id`, `consumidor_id`),
  INDEX `fk_cartao_consumidor_consumidor1_idx` (`consumidor_id` ASC),
  INDEX `fk_cartao_consumidor_cartao1_idx` (`cartao_id` ASC),
  CONSTRAINT `fk_cartao_consumidor_cartao1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `mine_apple`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartao_consumidor_consumidor1`
    FOREIGN KEY (`consumidor_id`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`assinatura_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`assinatura_produto` (
  `assinatura_id` INT NOT NULL,
  `compra_id` INT NOT NULL,
  `consumidor_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `produtor_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `frequencia` INT NOT NULL,
  `seg` TINYINT(1) NOT NULL,
  `ter` TINYINT(1) NOT NULL,
  `qua` TINYINT(1) NOT NULL,
  `qui` TINYINT(1) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `sab` TINYINT(1) NOT NULL,
  `dom` TINYINT(1) NOT NULL,
  PRIMARY KEY (`assinatura_id`, `compra_id`, `consumidor_id`, `produto_id`, `categoria_id`, `produtor_id`),
  INDEX `fk_assinatura_produto_produto1_idx` (`produto_id` ASC, `categoria_id` ASC, `produtor_id` ASC),
  CONSTRAINT `fk_assinatura_produto_assinatura1`
    FOREIGN KEY (`assinatura_id` , `compra_id` , `consumidor_id`)
    REFERENCES `mine_apple`.`assinatura` (`id` , `compra_id` , `consumidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assinatura_produto_produto1`
    FOREIGN KEY (`produto_id` , `categoria_id` , `produtor_id`)
    REFERENCES `mine_apple`.`produto` (`id` , `categoria_id` , `produtor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
