-- MySQL Script generated by MySQL Workbench
-- Wed 30 May 2018 06:03:08 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mine_apple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mine_apple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mine_apple` DEFAULT CHARACTER SET utf8 ;
USE `mine_apple` ;

-- -----------------------------------------------------
-- Table `mine_apple`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `senha` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `operacao` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`, `idUsuario`),
  INDEX `fk_log_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`administrador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrador_usuario`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `logradouro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `numero` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `complemento` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `cidade` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`produtor` (
  `id` INT NOT NULL,
  `idEndereco` INT NOT NULL,
  `cnpj` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nomeFantasia` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `razaoSocial` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `telefone` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `raioEntrega` INT NOT NULL,
  `acesso` TINYINT(1) NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_produtor_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_produtor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtor_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mine_apple`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`banco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idBanco` INT NOT NULL,
  `numero` INT NOT NULL,
  `agencia` INT NOT NULL,
  `digito` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_conta_banco1_idx` (`idBanco` ASC),
  CONSTRAINT `fk_conta_banco1`
    FOREIGN KEY (`idBanco`)
    REFERENCES `mine_apple`.`banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seg` TINYINT(1) NOT NULL,
  `ter` TINYINT(1) NOT NULL,
  `qua` TINYINT(1) NOT NULL,
  `qui` TINYINT(1) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `sab` TINYINT(1) NOT NULL,
  `dom` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProdutor` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idEntrega` INT NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `descricao` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `valor` DOUBLE NOT NULL,
  `minPorAssinatura` INT NOT NULL,
  `maxPorDia` INT NOT NULL,
  `freteMax` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_produtor1_idx` (`idProdutor` ASC),
  INDEX `fk_produto_categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_produto_entrega1_idx` (`idEntrega` ASC),
  CONSTRAINT `fk_produto_produtor1`
    FOREIGN KEY (`idProdutor`)
    REFERENCES `mine_apple`.`produtor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mine_apple`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_entrega1`
    FOREIGN KEY (`idEntrega`)
    REFERENCES `mine_apple`.`entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`consumidor` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sobrenome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `telefone` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `acesso` TINYINT(1) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_consumidor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mine_apple`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mine_apple`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `titular` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `validade` DATE NOT NULL,
  `codigo` INT NOT NULL,
  `credito` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idConsumidor` INT NOT NULL,
  `idEndereco` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_consumidor1_idx` (`idConsumidor` ASC),
  INDEX `fk_compra_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_compra_consumidor1`
    FOREIGN KEY (`idConsumidor`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mine_apple`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`assinatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `frequencia` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `notaFiscal` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assinatura_compra1_idx` (`idCompra` ASC),
  CONSTRAINT `fk_assinatura_compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `mine_apple`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAssinatura` INT NOT NULL,
  `idCartao` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_assinatura1_idx` (`idAssinatura` ASC),
  INDEX `fk_pagamento_cartao1_idx` (`idCartao` ASC),
  CONSTRAINT `fk_pagamento_assinatura1`
    FOREIGN KEY (`idAssinatura`)
    REFERENCES `mine_apple`.`assinatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_cartao1`
    FOREIGN KEY (`idCartao`)
    REFERENCES `mine_apple`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`avaliacao` (
  `idAssinatura` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `comentario` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  PRIMARY KEY (`idAssinatura`),
  CONSTRAINT `fk_avaliacao_assinatura1`
    FOREIGN KEY (`idAssinatura`)
    REFERENCES `mine_apple`.`assinatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProduto` INT NOT NULL,
  `path` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_foto_produto1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_foto_produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mine_apple`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`contaProdutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`contaProdutor` (
  `idConta` INT NOT NULL,
  `idProdutor` INT NOT NULL,
  PRIMARY KEY (`idConta`, `idProdutor`),
  INDEX `fk_conta_has_produtor_produtor1_idx` (`idProdutor` ASC),
  INDEX `fk_conta_has_produtor_conta1_idx` (`idConta` ASC),
  CONSTRAINT `fk_conta_has_produtor_conta1`
    FOREIGN KEY (`idConta`)
    REFERENCES `mine_apple`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_has_produtor_produtor1`
    FOREIGN KEY (`idProdutor`)
    REFERENCES `mine_apple`.`produtor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`cartaoConsumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`cartaoConsumidor` (
  `idCartao` INT NOT NULL,
  `idConsumidor` INT NOT NULL,
  PRIMARY KEY (`idCartao`, `idConsumidor`),
  INDEX `fk_cartao_has_consumidor_consumidor1_idx` (`idConsumidor` ASC),
  INDEX `fk_cartao_has_consumidor_cartao1_idx` (`idCartao` ASC),
  CONSTRAINT `fk_cartao_has_consumidor_cartao1`
    FOREIGN KEY (`idCartao`)
    REFERENCES `mine_apple`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartao_has_consumidor_consumidor1`
    FOREIGN KEY (`idConsumidor`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`produtoAssinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`produtoAssinatura` (
  `idProduto` INT NOT NULL,
  `idAssinatura` INT NOT NULL,
  `idEntrega` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `idAssinatura`),
  INDEX `fk_produto_has_assinatura_assinatura1_idx` (`idAssinatura` ASC),
  INDEX `fk_produto_has_assinatura_produto1_idx` (`idProduto` ASC),
  INDEX `fk_produtoAssinatura_entrega1_idx` (`idEntrega` ASC),
  CONSTRAINT `fk_produto_has_assinatura_produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mine_apple`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_assinatura_assinatura1`
    FOREIGN KEY (`idAssinatura`)
    REFERENCES `mine_apple`.`assinatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtoAssinatura_entrega1`
    FOREIGN KEY (`idEntrega`)
    REFERENCES `mine_apple`.`entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mine_apple`.`enderecoConsumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine_apple`.`enderecoConsumidor` (
  `idEndereco` INT NOT NULL,
  `idConsumidor` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `idConsumidor`),
  INDEX `fk_endereco_has_consumidor_consumidor1_idx` (`idConsumidor` ASC),
  INDEX `fk_endereco_has_consumidor_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_endereco_has_consumidor_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mine_apple`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_consumidor_consumidor1`
    FOREIGN KEY (`idConsumidor`)
    REFERENCES `mine_apple`.`consumidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
