<?php

use Illuminate\Database\Seeder;

class BancoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banco')->insert([
			 ['id' => 1, 'nome' => 'BANCO DO BRASIL S/A'],
			 ['id' => 2, 'nome' => 'BANCO CENTRAL DO BRASIL'],
			 ['id' => 3, 'nome' => 'BANCO DA AMAZONIA S.A'],
			 ['id' => 4, 'nome' => 'BANCO DO NORDESTE DO BRASIL S.A'],
			 ['id' => 7, 'nome' => 'BANCO NAC DESENV. ECO. SOCIAL S.A'],
			 ['id' => 8, 'nome' => 'BANCO MERIDIONAL DO BRASIL'],
			 ['id' => 20, 'nome' => 'BANCO DO ESTADO DE ALAGOAS S.A'],
			 ['id' => 21, 'nome' => 'BANCO DO ESTADO DO ESPIRITO SANTO S.A'],
			 ['id' => 22, 'nome' => 'BANCO DE CREDITO REAL DE MINAS GERAIS SA'],
			 ['id' => 24, 'nome' => 'BANCO DO ESTADO DE PERNAMBUCO'],
			 ['id' => 25, 'nome' => 'BANCO ALFA S/A'],
			 ['id' => 26, 'nome' => 'BANCO DO ESTADO DO ACRE S.A'],
			 ['id' => 27, 'nome' => 'BANCO DO ESTADO DE SANTA CATARINA S.A'],
			 ['id' => 28, 'nome' => 'BANCO DO ESTADO DA BAHIA S.A'],
			 ['id' => 29, 'nome' => 'BANCO DO ESTADO DO RIO DE JANEIRO S.A'],
			 ['id' => 30, 'nome' => 'BANCO DO ESTADO DA PARAIBA S.A'],
			 ['id' => 31, 'nome' => 'BANCO DO ESTADO DE GOIAS S.A'],
			 ['id' => 32, 'nome' => 'BANCO DO ESTADO DO MATO GROSSO S.A.'],
			 ['id' => 33, 'nome' => 'BANCO DO ESTADO DE SAO PAULO S.A'],
			 ['id' => 34, 'nome' => 'BANCO DO ESADO DO AMAZONAS S.A'],
			 ['id' => 35, 'nome' => 'BANCO DO ESTADO DO CEARA S.A'],
			 ['id' => 36, 'nome' => 'BANCO DO ESTADO DO MARANHAO S.A'],
			 ['id' => 37, 'nome' => 'BANCO DO ESTADO DO PARA S.A'],
			 ['id' => 38, 'nome' => 'BANCO DO ESTADO DO PARANA S.A'],
			 ['id' => 39, 'nome' => 'BANCO DO ESTADO DO PIAUI S.A'],
			 ['id' => 41, 'nome' => 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A'],
			 ['id' => 47, 'nome' => 'BANCO DO ESTADO DE SERGIPE S.A'],
			 ['id' => 48, 'nome' => 'BANCO DO ESTADO DE MINAS GERAIS S.A'],
			 ['id' => 59, 'nome' => 'BANCO DO ESTADO DE RONDONIA S.A'],
			 ['id' => 70, 'nome' => 'BANCO DE BRASILIA S.A'],
			 ['id' => 104, 'nome' => 'CAIXA ECONOMICA FEDERAL'],
			 ['id' => 106, 'nome' => 'BANCO ITABANCO S.A.'],
			 ['id' => 107, 'nome' => 'BANCO BBM S.A'],
			 ['id' => 109, 'nome' => 'BANCO CREDIBANCO S.A'],
			 ['id' => 116, 'nome' => 'BANCO B.N.L DO BRASIL S.A'],
			 ['id' => 148, 'nome' => 'MULTI BANCO S.A'],
			 ['id' => 151, 'nome' => 'CAIXA ECONOMICA DO ESTADO DE SAO PAULO'],
			 ['id' => 153, 'nome' => 'CAIXA ECONOMICA DO ESTADO DO R.G.SUL'],
			 ['id' => 165, 'nome' => 'BANCO NORCHEM S.A'],
			 ['id' => 166, 'nome' => 'BANCO INTER-ATLANTICO S.A'],
			 ['id' => 168, 'nome' => 'BANCO C.C.F. BRASIL S.A'],
			 ['id' => 175, 'nome' => 'CONTINENTAL BANCO S.A'],
			 ['id' => 184, 'nome' => 'BBA - CREDITANSTALT S.A'],
			 ['id' => 199, 'nome' => 'BANCO FINANCIAL PORTUGUES'],
			 ['id' => 200, 'nome' => 'BANCO FRICRISA AXELRUD S.A'],
			 ['id' => 201, 'nome' => 'BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A'],
			 ['id' => 204, 'nome' => 'BANCO S.R.L S.A'],
			 ['id' => 205, 'nome' => 'BANCO SUL AMERICA S.A'],
			 ['id' => 206, 'nome' => 'BANCO MARTINELLI S.A'],
			 ['id' => 208, 'nome' => 'BANCO PACTUAL S.A'],
			 ['id' => 210, 'nome' => 'DEUTSCH SUDAMERIKANICHE BANK AG'],
			 ['id' => 211, 'nome' => 'BANCO SISTEMA S.A'],
			 ['id' => 212, 'nome' => 'BANCO MATONE S.A'],
			 ['id' => 213, 'nome' => 'BANCO ARBI S.A'],
			 ['id' => 214, 'nome' => 'BANCO DIBENS S.A'],
			 ['id' => 215, 'nome' => 'BANCO AMERICA DO SUL S.A'],
			 ['id' => 216, 'nome' => 'BANCO REGIONAL MALCON S.A'],
			 ['id' => 217, 'nome' => 'BANCO AGROINVEST S.A'],
			 ['id' => 218, 'nome' => 'BBS - BANCO BONSUCESSO S.A.'],
			 ['id' => 219, 'nome' => 'BANCO DE CREDITO DE SAO PAULO S.A'],
			 ['id' => 220, 'nome' => 'BANCO CREFISUL'],
			 ['id' => 221, 'nome' => 'BANCO GRAPHUS S.A'],
			 ['id' => 222, 'nome' => 'BANCO AGF BRASIL S. A.'],
			 ['id' => 223, 'nome' => 'BANCO INTERUNION S.A'],
			 ['id' => 224, 'nome' => 'BANCO FIBRA S.A'],
			 ['id' => 225, 'nome' => 'BANCO BRASCAN S.A'],
			 ['id' => 228, 'nome' => 'BANCO ICATU S.A'],
			 ['id' => 229, 'nome' => 'BANCO CRUZEIRO S.A'],
			 ['id' => 230, 'nome' => 'BANCO BANDEIRANTES S.A'],
			 ['id' => 231, 'nome' => 'BANCO BOAVISTA S.A'],
			 ['id' => 232, 'nome' => 'BANCO INTERPART S.A'],
			 ['id' => 233, 'nome' => 'BANCO MAPPIN S.A'],
			 ['id' => 234, 'nome' => 'BANCO LAVRA S.A.'],
			 ['id' => 235, 'nome' => 'BANCO LIBERAL S.A'],
			 ['id' => 236, 'nome' => 'BANCO CAMBIAL S.A'],
			 ['id' => 237, 'nome' => 'BANCO BRADESCO S.A'],
			 ['id' => 239, 'nome' => 'BANCO BANCRED S.A'],
			 ['id' => 240, 'nome' => 'BANCO DE CREDITO REAL DE MINAS GERAIS S.'],
			 ['id' => 241, 'nome' => 'BANCO CLASSICO S.A'],
			 ['id' => 242, 'nome' => 'BANCO EUROINVEST S.A'],
			 ['id' => 243, 'nome' => 'BANCO STOCK S.A'],
			 ['id' => 244, 'nome' => 'BANCO CIDADE S.A'],
			 ['id' => 245, 'nome' => 'BANCO EMPRESARIAL S.A'],
			 ['id' => 246, 'nome' => 'BANCO ABC ROMA S.A'],
			 ['id' => 247, 'nome' => 'BANCO OMEGA S.A'],
			 ['id' => 249, 'nome' => 'BANCO INVESTCRED S.A'],
			 ['id' => 250, 'nome' => 'BANCO SCHAHIN CURY S.A'],
			 ['id' => 251, 'nome' => 'BANCO SAO JORGE S.A.'],
			 ['id' => 252, 'nome' => 'BANCO FININVEST S.A'],
			 ['id' => 254, 'nome' => 'BANCO PARANA BANCO S.A'],
			 ['id' => 255, 'nome' => 'MILBANCO S.A.'],
			 ['id' => 256, 'nome' => 'BANCO GULVINVEST S.A'],
			 ['id' => 258, 'nome' => 'BANCO INDUSCRED S.A'],
			 ['id' => 261, 'nome' => 'BANCO VARIG S.A'],
			 ['id' => 262, 'nome' => 'BANCO BOREAL S.A'],
			 ['id' => 263, 'nome' => 'BANCO CACIQUE'],
			 ['id' => 264, 'nome' => 'BANCO PERFORMANCE S.A'],
			 ['id' => 265, 'nome' => 'BANCO FATOR S.A'],
			 ['id' => 266, 'nome' => 'BANCO CEDULA S.A'],
			 ['id' => 267, 'nome' => 'BANCO BBM-COM.C.IMOB.CFI S.A.'],
			 ['id' => 275, 'nome' => 'BANCO REAL S.A'],
			 ['id' => 277, 'nome' => 'BANCO PLANIBANC S.A'],
			 ['id' => 282, 'nome' => 'BANCO BRASILEIRO COMERCIAL'],
			 ['id' => 291, 'nome' => 'BANCO DE CREDITO NACIONAL S.A'],
			 ['id' => 294, 'nome' => 'BCR - BANCO DE CREDITO REAL S.A'],
			 ['id' => 295, 'nome' => 'BANCO CREDIPLAN S.A'],
			 ['id' => 300, 'nome' => 'BANCO DE LA NACION ARGENTINA S.A'],
			 ['id' => 302, 'nome' => 'BANCO DO PROGRESSO S.A'],
			 ['id' => 303, 'nome' => 'BANCO HNF S.A.'],
			 ['id' => 304, 'nome' => 'BANCO PONTUAL S.A'],
			 ['id' => 308, 'nome' => 'BANCO COMERCIAL BANCESA S.A.'],
			 ['id' => 318, 'nome' => 'BANCO B.M.G. S.A'],
			 ['id' => 320, 'nome' => 'BANCO INDUSTRIAL E COMERCIAL'],
			 ['id' => 341, 'nome' => 'BANCO ITAU S.A'],
			 ['id' => 346, 'nome' => 'BANCO FRANCES E BRASILEIRO S.A'],
			 ['id' => 347, 'nome' => 'BANCO SUDAMERIS BRASIL S.A'],
			 ['id' => 351, 'nome' => 'BANCO BOZANO SIMONSEN S.A'],
			 ['id' => 353, 'nome' => 'BANCO GERAL DO COMERCIO S.A'],
			 ['id' => 356, 'nome' => 'ABN AMRO S.A'],
			 ['id' => 366, 'nome' => 'BANCO SOGERAL S.A'],
			 ['id' => 369, 'nome' => 'PONTUAL'],
			 ['id' => 370, 'nome' => 'BEAL - BANCO EUROPEU PARA AMERICA LATINA'],
			 ['id' => 372, 'nome' => 'BANCO ITAMARATI S.A'],
			 ['id' => 375, 'nome' => 'BANCO FENICIA S.A'],
			 ['id' => 376, 'nome' => 'CHASE MANHATTAN BANK S.A'],
			 ['id' => 388, 'nome' => 'BANCO MERCANTIL DE DESCONTOS S/A'],
			 ['id' => 389, 'nome' => 'BANCO MERCANTIL DO BRASIL S.A'],
			 ['id' => 392, 'nome' => 'BANCO MERCANTIL DE SAO PAULO S.A'],
			 ['id' => 394, 'nome' => 'BANCO B.M.C. S.A'],
			 ['id' => 399, 'nome' => 'BANCO BAMERINDUS DO BRASIL S.A'],
			 ['id' => 409, 'nome' => 'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS'],
			 ['id' => 412, 'nome' => 'BANCO NACIONAL DA BAHIA S.A'],
			 ['id' => 415, 'nome' => 'BANCO NACIONAL S.A'],
			 ['id' => 420, 'nome' => 'BANCO NACIONAL DO NORTE S.A'],
			 ['id' => 422, 'nome' => 'BANCO SAFRA S.A'],
			 ['id' => 424, 'nome' => 'BANCO NOROESTE S.A'],
			 ['id' => 434, 'nome' => 'BANCO FORTALEZA S.A'],
			 ['id' => 453, 'nome' => 'BANCO RURAL S.A'],
			 ['id' => 456, 'nome' => 'BANCO TOKIO S.A'],
			 ['id' => 464, 'nome' => 'BANCO SUMITOMO BRASILEIRO S.A'],
			 ['id' => 466, 'nome' => 'BANCO MITSUBISHI BRASILEIRO S.A'],
			 ['id' => 472, 'nome' => 'LLOYDS BANK PLC'],
			 ['id' => 473, 'nome' => 'BANCO FINANCIAL PORTUGUES S.A'],
			 ['id' => 477, 'nome' => 'CITIBANK N.A'],
			 ['id' => 479, 'nome' => 'BANCO DE BOSTON S.A'],
			 ['id' => 480, 'nome' => 'BANCO PORTUGUES DO ATLANTICO-BRASIL S.A'],
			 ['id' => 483, 'nome' => 'BANCO AGRIMISA S.A.'],
			 ['id' => 487, 'nome' => 'DEUTSCHE BANK S.A - BANCO ALEMAO'],
			 ['id' => 488, 'nome' => 'BANCO J. P. MORGAN S.A'],
			 ['id' => 489, 'nome' => 'BANESTO BANCO URUGAUAY S.A'],
			 ['id' => 492, 'nome' => 'INTERNATIONALE NEDERLANDEN BANK N.V.'],
			 ['id' => 493, 'nome' => 'BANCO UNION S.A.C.A'],
			 ['id' => 494, 'nome' => 'BANCO LA REP. ORIENTAL DEL URUGUAY'],
			 ['id' => 495, 'nome' => 'BANCO LA PROVINCIA DE BUENOS AIRES'],
			 ['id' => 496, 'nome' => 'BANCO EXTERIOR DE ESPANA S.A'],
			 ['id' => 498, 'nome' => 'CENTRO HISPANO BANCO'],
			 ['id' => 499, 'nome' => 'BANCO IOCHPE S.A'],
			 ['id' => 501, 'nome' => 'BANCO BRASILEIRO IRAQUIANO S.A.'],
			 ['id' => 502, 'nome' => 'BANCO SANTANDER S.A'],
			 ['id' => 504, 'nome' => 'BANCO MULTIPLIC S.A'],
			 ['id' => 505, 'nome' => 'BANCO GARANTIA S.A'],
			 ['id' => 600, 'nome' => 'BANCO LUSO BRASILEIRO S.A'],
			 ['id' => 601, 'nome' => 'BFC BANCO S.A.'],
			 ['id' => 602, 'nome' => 'BANCO PATENTE S.A'],
			 ['id' => 604, 'nome' => 'BANCO INDUSTRIAL DO BRASIL S.A'],
			 ['id' => 607, 'nome' => 'BANCO SANTOS NEVES S.A'],
			 ['id' => 608, 'nome' => 'BANCO OPEN S.A'],
			 ['id' => 610, 'nome' => 'BANCO V.R. S.A'],
			 ['id' => 611, 'nome' => 'BANCO PAULISTA S.A'],
			 ['id' => 612, 'nome' => 'BANCO GUANABARA S.A'],
			 ['id' => 613, 'nome' => 'BANCO PECUNIA S.A'],
			 ['id' => 616, 'nome' => 'BANCO INTERPACIFICO S.A'],
			 ['id' => 617, 'nome' => 'BANCO INVESTOR S.A.'],
			 ['id' => 618, 'nome' => 'BANCO TENDENCIA S.A'],
			 ['id' => 621, 'nome' => 'BANCO APLICAP S.A.'],
			 ['id' => 622, 'nome' => 'BANCO DRACMA S.A'],
			 ['id' => 623, 'nome' => 'BANCO PANAMERICANO S.A'],
			 ['id' => 624, 'nome' => 'BANCO GENERAL MOTORS S.A'],
			 ['id' => 625, 'nome' => 'BANCO ARAUCARIA S.A'],
			 ['id' => 626, 'nome' => 'BANCO FICSA S.A'],
			 ['id' => 627, 'nome' => 'BANCO DESTAK S.A'],
			 ['id' => 628, 'nome' => 'BANCO CRITERIUM S.A'],
			 ['id' => 629, 'nome' => 'BANCORP BANCO COML. E. DE INVESTMENTO'],
			 ['id' => 630, 'nome' => 'BANCO INTERCAP S.A'],
			 ['id' => 633, 'nome' => 'BANCO REDIMENTO S.A'],
			 ['id' => 634, 'nome' => 'BANCO TRIANGULO S.A'],
			 ['id' => 635, 'nome' => 'BANCO DO ESTADO DO AMAPA S.A'],
			 ['id' => 637, 'nome' => 'BANCO SOFISA S.A'],
			 ['id' => 638, 'nome' => 'BANCO PROSPER S.A'],
			 ['id' => 639, 'nome' => 'BIG S.A. - BANCO IRMAOS GUIMARAES'],
			 ['id' => 640, 'nome' => 'BANCO DE CREDITO METROPOLITANO S.A'],
			 ['id' => 641, 'nome' => 'BANCO EXCEL ECONOMICO S/A'],
			 ['id' => 643, 'nome' => 'BANCO SEGMENTO S.A'],
			 ['id' => 645, 'nome' => 'BANCO DO ESTADO DE RORAIMA S.A'],
			 ['id' => 647, 'nome' => 'BANCO MARKA S.A'],
			 ['id' => 648, 'nome' => 'BANCO ATLANTIS S.A'],
			 ['id' => 649, 'nome' => 'BANCO DIMENSAO S.A'],
			 ['id' => 650, 'nome' => 'BANCO PEBB S.A'],
			 ['id' => 652, 'nome' => 'BANCO FRANCES E BRASILEIRO SA'],
			 ['id' => 653, 'nome' => 'BANCO INDUSVAL S.A'],
			 ['id' => 654, 'nome' => 'BANCO A. J. RENNER S.A'],
			 ['id' => 655, 'nome' => 'BANCO VOTORANTIM S.A.'],
			 ['id' => 656, 'nome' => 'BANCO MATRIX S.A'],
			 ['id' => 657, 'nome' => 'BANCO TECNICORP S.A'],
			 ['id' => 658, 'nome' => 'BANCO PORTO REAL S.A'],
			 ['id' => 702, 'nome' => 'BANCO SANTOS S.A'],
			 ['id' => 705, 'nome' => 'BANCO INVESTCORP S.A.'],
			 ['id' => 707, 'nome' => 'BANCO DAYCOVAL S.A'],
			 ['id' => 711, 'nome' => 'BANCO VETOR S.A.'],
			 ['id' => 713, 'nome' => 'BANCO CINDAM S.A'],
			 ['id' => 715, 'nome' => 'BANCO VEGA S.A'],
			 ['id' => 718, 'nome' => 'BANCO OPERADOR S.A'],
			 ['id' => 719, 'nome' => 'BANCO PRIMUS S.A'],
			 ['id' => 720, 'nome' => 'BANCO MAXINVEST S.A'],
			 ['id' => 721, 'nome' => 'BANCO CREDIBEL S.A'],
			 ['id' => 722, 'nome' => 'BANCO INTERIOR DE SAO PAULO S.A'],
			 ['id' => 724, 'nome' => 'BANCO PORTO SEGURO S.A'],
			 ['id' => 725, 'nome' => 'BANCO FINABANCO S.A'],
			 ['id' => 726, 'nome' => 'BANCO UNIVERSAL S.A'],
			 ['id' => 728, 'nome' => 'BANCO FITAL S.A'],
			 ['id' => 729, 'nome' => 'BANCO FONTE S.A'],
			 ['id' => 730, 'nome' => 'BANCO COMERCIAL PARAGUAYO S.A'],
			 ['id' => 731, 'nome' => 'BANCO GNPP S.A.'],
			 ['id' => 732, 'nome' => 'BANCO PREMIER S.A.'],
			 ['id' => 733, 'nome' => 'BANCO NACOES S.A.'],
			 ['id' => 734, 'nome' => 'BANCO GERDAU S.A'],
			 ['id' => 735, 'nome' => 'BANCO NEON'],
			 ['id' => 736, 'nome' => 'BANCO UNITED S.A'],
			 ['id' => 737, 'nome' => 'THECA'],
			 ['id' => 738, 'nome' => 'MARADA'],
			 ['id' => 739, 'nome' => 'BGN'],
			 ['id' => 740, 'nome' => 'BCN BARCLAYS'],
			 ['id' => 741, 'nome' => 'BRP'],
			 ['id' => 742, 'nome' => 'EQUATORIAL'],
			 ['id' => 743, 'nome' => 'BANCO EMBLEMA S.A'],
			 ['id' => 744, 'nome' => 'THE FIRST NATIONAL BANK OF BOSTON'],
			 ['id' => 745, 'nome' => 'CITIBAN N.A.'],
			 ['id' => 746, 'nome' => 'MODAL S\A'],
			 ['id' => 747, 'nome' => 'RAIBOBANK DO BRASIL'],
			 ['id' => 748, 'nome' => 'SICREDI'],
			 ['id' => 749, 'nome' => 'BRMSANTIL SA'],
			 ['id' => 750, 'nome' => 'BANCO REPUBLIC NATIONAL OF NEW YORK'],
			 ['id' => 751, 'nome' => 'DRESDNER BANK LATEINAMERIKA-BRASIL S/A'],
			 ['id' => 752, 'nome' => 'BANCO BANQUE NATIONALE DE PARIS BRASIL S'],
			 ['id' => 753, 'nome' => 'BANCO COMERCIAL URUGUAI S.A.'],
			 ['id' => 755, 'nome' => 'BANCO MERRILL LYNCH S.A'],
			 ['id' => 756, 'nome' => 'BANCO COOPERATIVO DO BRASIL S.A.'],
			 ['id' => 757, 'nome' => 'BANCO KEB DO BRASIL S.A.'],
			 ['id' => 260, 'nome' => 'NUBANK S.A'],
			 ['id' => 102, 'nome' => 'XP INVESTIMENTOS']
    
]);
    }
}
